# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: flask-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5040
          env:
            - name: FIREBASE_CRED
              valueFrom:
                secretKeyRef:
                  name: firebase-secret  # name of the Secret
                  key: serviceAccountKey.json



---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5040
    protocol: TCP
    targetPort: 5040
  selector:
    app: flaskapi
  type: LoadBalancer