# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - default-pool
      containers:
        - name: flaskapi
          image: us-central1-docker.pkg.dev/amore-f8cd6/amore-microservices/flask-api:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5040
          env:
            - name: FIREBASE_CRED
              valueFrom:
                secretKeyRef:
                  name: firebase-secret  # name of the Secret
                  key: stagingServiceAccountKey.json



---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5040
    protocol: TCP
    targetPort: 5040
  selector:
    app: flaskapi
  type: LoadBalancer
  loadBalancerIP: "34.172.205.119"