name: Build and Push Amore Flask Image to Google Cloud Platform
on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flask-api
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Refer for guide on auth (Service Account Key JSON): https://github.com/google-github-actions/setup-gcloud#authorization
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      # - name: Automatic Tagging of Releases
      #   id: increment-git-tag
      #   run: |
      #     bash ./scripts/git_update.sh -v major
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      
      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: latest
        run: |-
          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/amore-microservices/$IMAGE_NAME:latest
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/amore-microservices/$IMAGE_NAME:latest
  
  deploy-to-gke:
    needs: build-push-gcr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.COMPUTE_ENGINE_SA_KEY }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: ${{ secrets.ZONE_NAME }}
      with:
        args: apply -f .
